Hotfix add notification v2
tim80411/twitter-api-2020 pull request #91
Opened 2021-07-25 13:05 UTC by ai285063

在 Notifications 加 isRead
修正了一下抓的 NotifyLabelId 值

2021-07-25 16:39 UTC, tim80411 commented on services/notificationService.js
> -    }
try catch原本是預期可以將過程中奇怪沒抓到的錯誤透過throw error丟出來，被刪除是因為他會額外造成錯誤嗎?

2021-07-25 16:41 UTC, tim80411 commented on services/notificationService.js
> +      NotifyLabelId: NotifyLabelId.dataValues.id
感謝修改，不過如果修改成這樣的話，我覺得在上面加raw，下面去掉dataValues直接取id更好，raw可以不把sql撈到的東西包成instance，效能會更好，而且這樣也更好閱讀。

2021-07-25 16:42 UTC, tim80411 requested changes
- 關於try catch的疑問
- 修改raw: true的部分

2021-07-25 16:42 UTC, tim80411 commented on services/notificationService.js
> -    }
像是資料庫失敗之類的

2021-07-25 22:15 UTC, ai285063 commented on services/notificationService.js
> -    }
在 controller 裡已經會抓錯誤了所以在 service 裡的 try catch 好像變小多餘（？

2021-07-25 22:15 UTC, ai285063 commented on services/notificationService.js
> +      NotifyLabelId: NotifyLabelId.dataValues.id
哦 有道理欸
那就這樣修吧

2021-07-26 03:39 UTC, tim80411 approved these changes

2021-07-26 03:39 UTC, merged